[scripts]
remove = "cargo remove"
add = "cargo add"
dev = "cargo run"
build = "cargo build"
lint = "cargo fmt --all"
install = "cargo install --path ."
clean = "cargo clean"
publish = "cargo publish"

[version]
bump = false